// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels(in *jlexer.Lexer, out *RegisterReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "role":
			out.Role = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels(out *jwriter.Writer, in RegisterReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegisterReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegisterReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegisterReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegisterReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels(l, v)
}
func easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels1(in *jlexer.Lexer, out *LoginReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels1(out *jwriter.Writer, in LoginReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels1(l, v)
}
func easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels2(in *jlexer.Lexer, out *DummyLoginReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "role":
			out.Role = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels2(out *jwriter.Writer, in DummyLoginReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DummyLoginReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DummyLoginReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1a2b04e0EncodeGithubComK1tten2005AvitoPvzInternalModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DummyLoginReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DummyLoginReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1a2b04e0DecodeGithubComK1tten2005AvitoPvzInternalModels2(l, v)
}
