// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson232327a2DecodeGithubComK1tten2005AvitoPvzInternalModels(in *jlexer.Lexer, out *PVZ) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Id).UnmarshalText(data))
			}
		case "registration_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.RegistrationDate).UnmarshalJSON(data))
			}
		case "city":
			out.City = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson232327a2EncodeGithubComK1tten2005AvitoPvzInternalModels(out *jwriter.Writer, in PVZ) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.Id).MarshalText())
	}
	{
		const prefix string = ",\"registration_date\":"
		out.RawString(prefix)
		out.Raw((in.RegistrationDate).MarshalJSON())
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PVZ) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson232327a2EncodeGithubComK1tten2005AvitoPvzInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PVZ) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson232327a2EncodeGithubComK1tten2005AvitoPvzInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PVZ) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson232327a2DecodeGithubComK1tten2005AvitoPvzInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PVZ) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson232327a2DecodeGithubComK1tten2005AvitoPvzInternalModels(l, v)
}
