// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels(in *jlexer.Lexer, out *Reception) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Id).UnmarshalText(data))
			}
		case "reception_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ReceptionTime).UnmarshalJSON(data))
			}
		case "pvzid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.PvzId).UnmarshalText(data))
			}
		case "products":
			if in.IsNull() {
				in.Skip()
				out.Products = nil
			} else {
				in.Delim('[')
				if out.Products == nil {
					if !in.IsDelim(']') {
						out.Products = make([]Product, 0, 0)
					} else {
						out.Products = []Product{}
					}
				} else {
					out.Products = (out.Products)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Product
					(v1).UnmarshalEasyJSON(in)
					out.Products = append(out.Products, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "status":
			out.Status = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels(out *jwriter.Writer, in Reception) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.Id).MarshalText())
	}
	{
		const prefix string = ",\"reception_time\":"
		out.RawString(prefix)
		out.Raw((in.ReceptionTime).MarshalJSON())
	}
	{
		const prefix string = ",\"pvzid\":"
		out.RawString(prefix)
		out.RawText((in.PvzId).MarshalText())
	}
	{
		const prefix string = ",\"products\":"
		out.RawString(prefix)
		if in.Products == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Products {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Reception) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Reception) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Reception) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Reception) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels(l, v)
}
func easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels1(in *jlexer.Lexer, out *Product) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Id).UnmarshalText(data))
			}
		case "reception_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ReceptionTime).UnmarshalJSON(data))
			}
		case "category":
			out.Category = string(in.String())
		case "reception_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ReceptionId).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels1(out *jwriter.Writer, in Product) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.Id).MarshalText())
	}
	{
		const prefix string = ",\"reception_time\":"
		out.RawString(prefix)
		out.Raw((in.ReceptionTime).MarshalJSON())
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"reception_id\":"
		out.RawString(prefix)
		out.RawText((in.ReceptionId).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Product) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Product) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson26500425EncodeGithubComK1tten2005AvitoPvzInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Product) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Product) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson26500425DecodeGithubComK1tten2005AvitoPvzInternalModels1(l, v)
}
